// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CsProjFormatter.Commands
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCsProjFormatterPackageString = "a02f620d-a31a-46a3-b2f5-7a0e214830f8";
        public static Guid guidCsProjFormatterPackage = new Guid(guidCsProjFormatterPackageString);

        public const string guidCsProjFormatterCmdSetString = "96f15caa-cbdc-4ddf-8f33-d44c16cb50dc";
        public static Guid guidCsProjFormatterCmdSet = new Guid(guidCsProjFormatterCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FormatAllGroup = 0x1020;
        public const int cmdidFormatAll = 0x0100;
    }
}
