<Project>
  <PropertyGroup>
    <Version>0.1</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'CsProjFormatter.Cli'">
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts\</ArtifactsPath>
  </PropertyGroup>
</Project>
