<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CsProjFormatter.Cli</RootNamespace>
    <AssemblyName>CsProjFormatter.Cli</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CsProjFormatter.Core\CsProjFormatter.Core.csproj" />
  </ItemGroup>

  <Target Name="CreateCompactExeAlias" AfterTargets="Build">
    <Copy
      SourceFiles="$(TargetDir)$(AssemblyName).exe"
      DestinationFiles="$(TargetDir)csprojfmt.exe"
      Condition="Exists('$(TargetDir)$(AssemblyName).exe')" />
  </Target>
</Project>
