// Copyright (c) 2026 by Stefan Egli.All rights reserved

// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CsProjFormatter
{
    internal sealed partial class Vsix
    {
        public const string Id = "CsProjFormatter.C4817943-A856-49E2-A982-5FC24F7ABE7C";
        public const string Name = "CsProjFormatter";
        public const string Description = @"Formats .csproj files: Sorts elements alphabetically";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Stefan Egli";
        public const string Tags = "csproj, formatting";
    }
}
