// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CsProjFormatter
{
    internal sealed partial class Vsix
    {
        public const string Id = "CsProjFormatter.C4817943-A856-49E2-A982-5FC24F7ABE7C";
        public const string Name = "CsProjFormatter";
        public const string Description = @"Formats .csproj files: Sorts elements alphabetically";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Stefan Egli";
        public const string Tags = "csproj, formatting";
        public const bool IsPreview = false;
    }
}
